### ISSUE TITLE
rank_neural_networks

### ISSUE THREAD

**Issue by brucewlee** [jlee118/NPRM#2]
Hello. I read your ACL paper. It really is good work. While looking through your code, I found the following line. What is "rank_neural_networks"? I don't find it in PyPI either.

from rank_neural_networks import BertRank, BertRank2

**Comment by brucewlee** [comment]
Also to add, if the labels are given 0 or 1 according to the respective passage's readability, how is NPRM so different from simple pairwise classification?

**Comment by jlee118** [comment]
Hi Bruce,

Re: rank_neural_networks, that is a mistake, I will remove it soon.  There is nothing there that affects how any of the code would work.

Re: simple pairwise classification, you are right, NPRM would be an instance of pairwise classification.  The novelty of our paper is that we propose using a fine-tuned BERT for pairwise classification; we also construct our labels through a sampled ordering to create the binary labels.  We also compared pairwise classification methods using pairwise SVM and various word-embeddings as features.

**Comment by brucewlee** [comment]
Thanks for the answer!
